# .goreleaser.yml
# Build customization
builds:
  - main: main.go
    binary: teamwork-go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux

release:
  github:
    owner: gabeduke
    name: teamwork-go